Repository celestiaorg/nmt, pull requests merged in 2023-08, with the labels that each got.

#230 chore: bump to Go 1.21
  .github/workflows/go.yml
  README.md
  go.mod
  nmt_test.go
Labels: chore

#229 docs: add a table for alternative implementations
  README.md
Labels: documentation

#232 refactor(pb/proof.go)!: converting pb definition to use snake_case
  pb/proof.pb.go
  pb/proof.proto
Labels: breaking
