Repository celestiaorg/nmt, pull requests merged in 2023-05, with the labels that each got.

#184 feat!: handles empty proofs in validateLeafHash and VerifyInclusion
  proof.go
  proof_test.go
Labels: enhancement

#185 feat: verifies namespace hash format to prevent panic in validateSiblingsNamespaceOrder
  hasher.go
  hasher_test.go
Labels: enhancement

#189 feat: export `VerifyLeafHashes`
  proof.go
  proof_test.go
Labels: enhancement, API

#186 feat: verifies input range in the computeRoot to avoid panic
  nmt.go
  nmt_test.go
Labels: enhancement

#187 feat: verifies the namespace order for each tree node
  hasher.go
  hasher_test.go
  proof_test.go
Labels: enhancement

#191 feat: adds the Size() method to the nmt API
  nmt.go
Labels: API

#192 feat!: add an additional constraint of empty leafHash field to the empty proof definition
  proof.go
  proof_test.go
Labels: enhancement

#188 feat: ensures consistent use of the assumption that NMT nodes are ordered ascendingly
  hasher.go
  hasher_test.go
Labels: enhancement

#198 feat: uses int instead of uint64 for leaves index
  nmt.go
Labels: enhancement

#199 chore: aligns the Ignore Max Namespace description with the implementation
  docs/nmt-lib.md
Labels: documentation

#201 Add HexString method for namespace id
  namespace/id.go
  namespace/id_test.go
Labels: enhancement
