Repository celestiaorg/nmt, pull requests merged in 2023-06, with the labels that each got.

#203 test: ExampleNamespacedMerkleTree
  nmt_test.go
Labels: enhancement

#202 feat!: hex encode `id.String()` output
  namespace/id.go
  namespace/id_test.go
Labels: enhancement

#209 doc: introduces short namespace absence proof in the NMT specs
  docs/spec/nmt.md
Labels: documentation, enhancement

#215 doc: aligns the nmt API doc with the current implementation
  README.md
  docs/nmt-lib.md
Labels: documentation
